-- CRIA TABELA PRODUCTS
-- Table: public.products

-- DROP TABLE IF EXISTS public.products;

CREATE TABLE IF NOT EXISTS public.products
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    description character varying(200) COLLATE pg_catalog."default",
    product_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    value numeric(38,2) NOT NULL,
    CONSTRAINT products_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.products
    OWNER to postgres;


-- CRIA TABELA ORDERS
-- Table: public.orders

-- DROP TABLE IF EXISTS public.orders;

CREATE TABLE IF NOT EXISTS public.orders
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    order_client character varying(255) COLLATE pg_catalog."default" NOT NULL,
    order_date character varying(255) COLLATE pg_catalog."default" NOT NULL,
    order_number character varying(255) COLLATE pg_catalog."default" NOT NULL,
    order_value numeric(38,2),
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT uknthkiu7pgmnqnu86i2jyoe2v7 UNIQUE (order_number)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.orders
    OWNER to postgres;



-- CRIA TABELA DE JOIN 
-- Table: public.order_products

-- DROP TABLE IF EXISTS public.order_products;

CREATE TABLE IF NOT EXISTS public.order_products
(
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT fkawxpt1ns1sr7al76nvjkv21of FOREIGN KEY (order_id)
        REFERENCES public.orders (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkdxjduvg7991r4qja26fsckxv8 FOREIGN KEY (product_id)
        REFERENCES public.products (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.order_products
    OWNER to postgres;