version: '3.8'

volumes:
  data:

networks:
  orders_net:

services:
  database:
    image: postgres:13
    ports: 
      - 5438:5432
    environment:
      - POSTGRES_DB:order_db
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./criar_database.sql:/docker-entrypoint-initdb.d/criar_database.sql
      - data:/data-docker/postgresql-data/data
      - type: tmpfs
        target: /dev/shm
    networks:
      - orders_net   

  rabbitmq:
    image: rabbitmq:4.0-management
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./data-docker/rabbitmq-data/data
        - ./data-docker/rabbitmq-data/log
    networks:
      - orders_net

  order:
    image: order/app
    build: ../order-v2
    depends_on:
      - database
      - rabbitmq
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/order_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - orders_net  

  sub-order:
    image: sub-order/app
    build: ../sub-order
    depends_on:
      - database
      - rabbitmq
    ports:
      - 8081:8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/order_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - orders_net