spring:
  datasource:
    driver-class-name: org.postgresql.Driver  
    url: jdbc:postgresql://localhost:5438/order_db #?useTimezone=true&serverTime=UTC
    username: postgres
    password: 123456
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
    generate-ddl: true
      
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq 

springdoc:
  api-docs:
   path: /v1/api-docs
   enabled: true
  swagger-ui:
    path: order-docapi
